use std::{
    env, fs,
    io::{self, IsTerminal, Write},
    path::{Path, PathBuf},
    process::Command,
};

use clap::CommandFactory;
use dialoguer::{Confirm, Input, Select};

use crate::cli::{Cli, CompletionCommand, InstallShell};

const BEGIN: &str = "# >>> tora completion >>>";
const END: &str = "# <<< tora completion <<<";
const PATH_PREFIX: &str = "# tora completion path: ";
const OWNER: &str = "# Generated by tora completion install.\n";

pub fn run(command: CompletionCommand) -> io::Result<()> {
    use CompletionCommand::*;
    let shell = match command {
        Bash => clap_complete::Shell::Bash,
        Zsh => clap_complete::Shell::Zsh,
        Fish => clap_complete::Shell::Fish,
        Powershell => clap_complete::Shell::PowerShell,
        Elvish => clap_complete::Shell::Elvish,
        Install { shell, path, yes } => return install(shell, path, yes),
    };
    clap_complete::generate(shell, &mut Cli::command(), "tora", &mut io::stdout());
    Ok(())
}

impl InstallShell {
    fn name(self) -> &'static str {
        match self {
            Self::Bash => "bash",
            Self::Zsh => "zsh",
        }
    }
}

fn shell_name(value: &str) -> Option<InstallShell> {
    match Path::new(value.trim())
        .file_name()?
        .to_str()?
        .trim_start_matches('-')
    {
        "bash" => Some(InstallShell::Bash),
        "zsh" => Some(InstallShell::Zsh),
        _ => None,
    }
}

fn ps_field(field: &str, pid: &str) -> Option<String> {
    let output = Command::new("ps")
        .args(["-p", pid, "-o", field])
        .output()
        .ok()?;
    output
        .status
        .success()
        .then(|| String::from_utf8_lossy(&output.stdout).trim().to_owned())
}

fn detect_shell() -> Option<InstallShell> {
    let parent = ps_field("ppid=", &std::process::id().to_string());
    parent
        .and_then(|pid| ps_field("comm=", &pid))
        .and_then(|name| shell_name(&name))
        .or_else(|| env::var("SHELL").ok().and_then(|name| shell_name(&name)))
}

fn absolute(path: &Path, home: &Path) -> io::Result<PathBuf> {
    let path = if path == Path::new("~") {
        home.to_owned()
    } else if let Ok(rest) = path.strip_prefix("~/") {
        home.join(rest)
    } else if path.is_absolute() {
        path.to_owned()
    } else {
        env::current_dir()?.join(path)
    };
    let text = path
        .to_str()
        .ok_or_else(|| io::Error::other("path must be valid UTF-8"))?;
    if text.chars().any(char::is_control) {
        return Err(io::Error::other("path must not contain control characters"));
    }
    Ok(path)
}

fn quote(path: &Path) -> String {
    format!(
        "'{}'",
        path.to_str()
            .expect("validated path")
            .replace('\'', "'\\''")
    )
}

fn read(path: &Path) -> io::Result<Option<String>> {
    match fs::read_to_string(path) {
        Ok(text) => Ok(Some(text)),
        Err(error) if error.kind() == io::ErrorKind::NotFound => {
            // A dangling symlink is not an absent file that we may replace.
            if fs::symlink_metadata(path).is_ok() {
                return Err(io::Error::other(format!(
                    "broken symlink: {}",
                    path.display()
                )));
            }
            Ok(None)
        }
        Err(error) => Err(error),
    }
}

fn block_range(text: &str) -> io::Result<Option<std::ops::Range<usize>>> {
    let starts: Vec<_> = text.match_indices(BEGIN).collect();
    let ends: Vec<_> = text.match_indices(END).collect();
    match (starts.as_slice(), ends.as_slice()) {
        ([], []) => Ok(None),
        ([(start, _)], [(end, _)]) if start < end => {
            let finish = end + END.len();
            if (*start != 0 && !text[..*start].ends_with('\n'))
                || (*end != 0 && !text[..*end].ends_with('\n'))
                || !text[*start + BEGIN.len()..].starts_with('\n')
                || (!text[finish..].is_empty() && !text[finish..].starts_with('\n'))
            {
                return Err(io::Error::other(
                    "invalid tora completion markers; repair the startup file first",
                ));
            }
            Ok(Some(*start..finish))
        }
        _ => Err(io::Error::other(
            "duplicate or incomplete tora completion markers; repair the startup file first",
        )),
    }
}

fn unmanaged(text: &str) -> bool {
    text.lines().any(|line| {
        let line = line.trim();
        !line.starts_with('#')
            && line.contains("tora")
            && (line.contains("completion") || line.contains("_tora") || line.contains("complete "))
    })
}

fn loader(shell: InstallShell) -> String {
    let name = shell.name();
    let init = if shell == InstallShell::Zsh {
        "    if ! (( $+functions[compdef] )); then\n        autoload -Uz compinit\n        compinit\n    fi\n    (( $+functions[compdef] )) || return\n"
    } else {
        ""
    };
    format!(
        "{OWNER}# Shell: {name}\n# Generate completion from the current tora on each new shell.\nif [[ -z ${{_TORA_COMPLETION_{name}_LOADED-}} ]] && command -v tora >/dev/null 2>&1; then\n{init}    if _tora_completion_script=$(command tora completion {name}); then\n        eval \"$_tora_completion_script\"\n        _TORA_COMPLETION_{name}_LOADED=1\n    fi\n    unset _tora_completion_script\nfi\n"
    )
}

struct Change {
    path: PathBuf,
    before: Option<String>,
    after: String,
}

impl Change {
    fn new(path: PathBuf, after: String) -> io::Result<Self> {
        let before = read(&path)?;
        // Follow dotfile symlinks without replacing the link itself.
        let path = if before.is_some() {
            fs::canonicalize(path)?
        } else {
            path
        };
        Ok(Self {
            path,
            before,
            after,
        })
    }

    fn changed(&self) -> bool {
        self.before.as_deref() != Some(&self.after)
    }
}

fn startup_files(shell: InstallShell, home: &Path) -> io::Result<Vec<PathBuf>> {
    if shell == InstallShell::Zsh {
        let directory = env::var_os("ZDOTDIR")
            .map(PathBuf::from)
            .unwrap_or_else(|| home.to_owned());
        return Ok(vec![absolute(&directory.join(".zshrc"), home)?]);
    }
    // Login Bash reads only the first existing file in this order. Install a
    // guarded loader there too, without sourcing arbitrary .bashrc content.
    let mut files = vec![home.join(".bashrc")];
    let login = [".bash_profile", ".bash_login", ".profile"]
        .into_iter()
        .map(|name| home.join(name))
        .find(|path| path.exists() || path.is_symlink())
        .unwrap_or_else(|| home.join(".bash_profile"));
    files.push(login);
    Ok(files)
}

fn install(shell: Option<InstallShell>, path: Option<PathBuf>, yes: bool) -> io::Result<()> {
    let interactive = io::stdin().is_terminal() && io::stderr().is_terminal();
    if !interactive && !yes {
        return Err(io::Error::other(
            "interactive terminal required; use --shell zsh|bash --yes for unattended installation",
        ));
    }
    let shell = match shell.or_else(detect_shell) {
        Some(shell) => shell,
        None => match Select::new()
            .with_prompt("Shell (Esc/q to cancel)")
            .items(["zsh", "bash"])
            .default(0)
            .interact_opt()
            .map_err(io::Error::other)?
        {
            Some(0) => InstallShell::Zsh,
            Some(_) => InstallShell::Bash,
            None => return Ok(()),
        },
    };
    eprintln!("Shell: {} (override with --shell)", shell.name());
    let home = env::var_os("HOME")
        .map(PathBuf::from)
        .ok_or_else(|| io::Error::other("HOME is required"))?;
    if !home.is_absolute() {
        return Err(io::Error::other("HOME must be an absolute path"));
    }
    let home = absolute(&home, &home)?;
    let files = startup_files(shell, &home)?;
    let mut existing_path = None;
    for file in &files {
        let text = read(file)?.unwrap_or_default();
        let range = block_range(&text)?;
        let outside = match range {
            Some(range) => {
                let stored = text[range.clone()]
                    .lines()
                    .find_map(|line| line.strip_prefix(PATH_PREFIX))
                    .ok_or_else(|| {
                        io::Error::other("managed completion block has no saved path")
                    })?;
                let stored = absolute(Path::new(stored), &home)?;
                if existing_path
                    .as_ref()
                    .is_some_and(|previous| previous != &stored)
                {
                    return Err(io::Error::other(
                        "startup files refer to different completion paths; reconcile them first",
                    ));
                }
                existing_path = Some(stored);
                format!("{}{}", &text[..range.start], &text[range.end..])
            }
            None => text,
        };
        if unmanaged(&outside) {
            return Err(io::Error::other(format!(
                "existing unmanaged tora completion in {}; keep it or remove it manually before installing",
                file.display()
            )));
        }
    }
    let root = env::var_os("TORA_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|| home.join(".tora"));
    let default = absolute(&root.join("completions").join(shell.name()), &home)?;
    let destination = match path.or(existing_path.clone()) {
        Some(path) => absolute(&path, &home)?,
        None if yes => default,
        None => {
            eprintln!("Existing completion configuration: none");
            let input: String = Input::new()
                .with_prompt("Completion loader file")
                .default(default.display().to_string())
                .interact_text()
                .map_err(io::Error::other)?;
            absolute(Path::new(&input), &home)?
        }
    };
    if destination.is_symlink() {
        return Err(io::Error::other("completion loader must not be a symlink"));
    }
    if let Some(text) = read(&destination)? {
        if !text.starts_with(OWNER) {
            return Err(io::Error::other(format!(
                "refusing to overwrite unmanaged file: {}",
                destination.display()
            )));
        }
        if !text
            .lines()
            .any(|line| line == format!("# Shell: {}", shell.name()))
        {
            return Err(io::Error::other(
                "completion loader belongs to a different shell; choose another --path",
            ));
        }
    }
    let mut changes = vec![Change::new(destination.clone(), loader(shell))?];
    let block = format!(
        "{BEGIN}\n{PATH_PREFIX}{}\nif [ -n \"${{{}-}}\" ] && [ -r {} ]; then\n    . {}\nfi\n{END}",
        destination.display(),
        if shell == InstallShell::Bash {
            "BASH_VERSION"
        } else {
            "ZSH_VERSION"
        },
        quote(&destination),
        quote(&destination)
    );
    for file in files {
        let before = read(&file)?.unwrap_or_default();
        let after = match block_range(&before)? {
            Some(range) => format!(
                "{}{}{}",
                &before[..range.start],
                block,
                &before[range.end..]
            ),
            None => format!(
                "{}{}{}\n",
                before,
                if before.is_empty() || before.ends_with('\n') {
                    ""
                } else {
                    "\n"
                },
                block
            ),
        };
        changes.push(Change::new(file, after)?);
    }
    // Two startup paths may point to the same dotfile. Identical changes are
    // safe to coalesce; a loader/startup collision is never safe.
    let mut unique: Vec<Change> = Vec::new();
    for change in changes {
        if let Some(previous) = unique.iter().find(|previous| previous.path == change.path) {
            if previous.after != change.after {
                return Err(io::Error::other(
                    "completion and startup file paths overlap",
                ));
            }
        } else {
            unique.push(change);
        }
    }
    let changes: Vec<_> = unique.into_iter().filter(Change::changed).collect();
    if changes.is_empty() {
        eprintln!(
            "Completion is already installed and up to date: {}",
            destination.display()
        );
        return Ok(());
    }
    eprintln!("Files to create/update:");
    for change in &changes {
        eprintln!("  {}", change.path.display());
    }
    if !yes
        && !Confirm::new()
            .with_prompt("Install completion?")
            .default(false)
            .interact()
            .map_err(io::Error::other)?
    {
        eprintln!("Cancelled; no files changed.");
        return Ok(());
    }
    apply(&changes)?;
    eprintln!(
        "Completion installed. Open a new {} shell, or run:\n  source {}",
        shell.name(),
        quote(&destination)
    );
    if existing_path
        .as_ref()
        .is_some_and(|old| old != &destination)
    {
        eprintln!(
            "The previous loader was retained; it is no longer referenced by the managed configuration."
        );
    }
    Ok(())
}

fn stage(change: &Change) -> io::Result<tempfile::NamedTempFile> {
    let parent = change
        .path
        .parent()
        .ok_or_else(|| io::Error::other("file has no parent directory"))?;
    fs::create_dir_all(parent)?;
    let mut temporary = tempfile::NamedTempFile::new_in(parent)?;
    if change.before.is_some() {
        temporary
            .as_file()
            .set_permissions(fs::metadata(&change.path)?.permissions())?;
    }
    temporary.write_all(change.after.as_bytes())?;
    temporary.as_file().sync_all()?;
    Ok(temporary)
}

fn apply(changes: &[Change]) -> io::Result<()> {
    // Prepare all writes first, so an unwritable destination does not leave a
    // startup file pointing at a loader that could not be written.
    let staged = changes.iter().map(stage).collect::<io::Result<Vec<_>>>()?;
    for change in changes {
        if read(&change.path)? != change.before {
            return Err(io::Error::other(format!(
                "{} changed during installation; retry",
                change.path.display()
            )));
        }
    }
    for (index, (change, temporary)) in changes.iter().zip(staged).enumerate() {
        if let Err(error) = temporary.persist(&change.path) {
            let mut failures = Vec::new();
            for previous in changes[..index].iter().rev() {
                let restored = match &previous.before {
                    Some(before) => stage(&Change {
                        path: previous.path.clone(),
                        before: Some(previous.after.clone()),
                        after: before.clone(),
                    })
                    .and_then(|file| {
                        file.persist(&previous.path)
                            .map(|_| ())
                            .map_err(|e| e.error)
                    }),
                    None => fs::remove_file(&previous.path),
                };
                if let Err(error) = restored {
                    failures.push(format!("{}: {error}", previous.path.display()));
                }
            }
            return Err(io::Error::other(format!(
                "could not update {}: {}; rollback errors: {:?}",
                change.path.display(),
                error.error,
                failures
            )));
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_supported_shell_names_only() {
        assert_eq!(shell_name("/bin/zsh"), Some(InstallShell::Zsh));
        assert_eq!(shell_name("-bash"), Some(InstallShell::Bash));
        assert_eq!(shell_name("fish"), None);
        assert_eq!(shell_name("bash-helper"), None);
    }

    #[test]
    fn rejects_damaged_or_duplicate_managed_blocks() {
        for text in [
            BEGIN.to_owned(),
            END.to_owned(),
            format!("{END}\n{BEGIN}"),
            format!("{BEGIN}\n{END}\n{BEGIN}\n{END}"),
            format!("echo '{BEGIN}\n{END}'"),
        ] {
            assert!(block_range(&text).is_err(), "{text}");
        }
    }
}
